# Generated by Django 3.1 on 2020-05-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200512_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_edit_author', 'Edit author info'),)},
        ),
    ]
