# Generated by Django 3.1 on 2020-05-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200523_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_edit_author', 'Create/Update/Delete author'),)},
        ),
    ]
